const TicketData = [
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
        comment : 'Hello. Is there a way of changing the way the mobile menu shows on mobile? In the desktop version there are many options: "slide out from side, slide out from side hover triggered, fullscreen cover slide + blur..... etc",No matter what option I select, the menu on mobile always acts the same way. Can I change this? Thank you!'
    },
    {
        id: 2,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'themes',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
        comment : ' mobile? In the desktop version there are many options: "slide out from side, slide out from side hover triggered, fullscreen cover slide + blur..... etc",No matter what option I select, the menu on mobile always acts the same way. Can I change this? Thank you!'
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'general',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
        comment : 'Hello. Is there a way of changing the way the mobile menu shows on mobile? In the desktop version there are many options: "slide out from side, slide out from side hover triggered, fullscreen cover slide + blur..... etc",No matter what option I select, the menu on mobile always acts the same way. Can I change this? Thank you!'
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
        comment : 'Hello. Is there a way of changing the way the mobile menu shows on mobile? In the desktop version there are many options: "slide out from side, slide out from side hover triggered, fullscreen cover slide + blur..... etc",No matter what option I select, the menu on mobile always acts the same way. Can I change this? Thank you!'
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
        comment : 'Hello. Is there a way of changing the way the mobile menu shows on mobile? In the desktop version there are many options: "slide out from side, slide out from side hover triggered, fullscreen cover slide + blur..... etc",No matter what option I select, the menu on mobile always acts the same way. Can I change this? Thank you!'
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 3,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    {
        id: 1,
        avatar: require('../../assets/avatar.webp'),
        thumbnail: require('../../assets/8794872685.png'),
        customer: 'maryam',
        shop: 'shope',
        categoryName: 'General',
        updatedAgo: 'updated 1 min ago',
        commentCount: 2,
    },
    // ... Other ticket objects
];
export default TicketData;